title: Reno Real Estate Team
author:
  name: Reno Real Estate Team
  email: 'javascript.uiux@gmail.com'
metadata:
    description: 'Real Estate business template'
    
# Site settings
title: Real Estate Template
email: javascript.uiux@gmail.com
description: "A real estate business template website built by Julius Alvarado w/The Grav CMS"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "https://www.facebook.com/profile.php?id=100006703996427"
     icon: facebook
  -  url: "https://twitter.com/ideaguy3d"
     icon: twitter
  -  url: "https://plus.google.com/u/0/112344297862530715288/posts/p/pub"
     icon: google-plus

footer: 
  text: "We find your perfect home."
  address:
    title: Visit Us
    lines:
      - line: 605 N El Dorado St
      - line: Stockton, CA
      - line: 95202 US
  social_title: Socialize
  contact:
    title: Contact
    lines:
      - text: 209-111-2222
        url: "#"
      - text: agent@realestate.com
        url: "agent@realestate.com"
