title: Julius
author:
  name: Julius Alvarado
  email: 'javascript.uiux@gmail.com'
metadata:
    description: 'Built by Julius Alvarado w/ The Grav CMS'


#One page menu scrolling
menu:
  - text: Features
    link: "#features"
  - text: Contact Me
    link: "#contact"

